- name: Make sure that old CA directory is deleted
  file:
    state: absent
    path: "{{ easy_rsa_directory_path }}"
  tags:
    - remove-openvpn-ca-directory

- name: Make sure that new CA directory exists
  shell: "mkdir {{ easy_rsa_directory_path }}"
  tags:
    - create-openvpn-ca-directory

- name: Link easyrsa script that the package installed into the ~/easy-rsa directory
  shell: "ln -s /usr/share/easy-rsa/* {{ easy_rsa_directory_path }}/"
  tags:
    - link-ca-directory

- name: Ensure that ~/easy-rsa owner is a non-root user with sudo privilege
  file:
    path: "{{ easy_rsa_directory_path }}"
    group: "{{ remote_user }}"
    owner: "{{ remote_user }}"
    state: directory
    mode: 0700

- name: Ensure that ~/easy-rsa/vars exists
  file:
    path: "{{ easy_rsa_directory_path }}/vars"
    group: "{{ remote_user }}"
    owner: "{{ remote_user }}"
    state: touch
