- name: Make sure that open ssh keys are generated on the CA server
  openssh_keypair:
    path: "{{ ssh_directory_path }}/id_rsa.openvpn"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0600
    state: present
    type: rsa

- name: Download the public key and save it in the /tmp
  fetch:
    src: "{{ ssh_directory_path }}/id_rsa.openvpn.pub"
    dest: /tmp/
    fail_on_missing: yes
    flat: yes
